### ISSUE TITLE
Threading?

### ISSUE THREAD

**Issue by esbe1175** [jfd02/tft-shop-assist#1]
Yo, i've been wondering if you'll be adding threading anytime soon?

It's fast enough that it is convenient to use if youre playing some brainless premade comp and just wanna think less, but it's not quite fast enough for Think Fast to REALLY be powerful in combo with this.

Apologize if i was supposed to ask this in a different place, but couldn't really figure out how.

**Comment by jfd02** [comment]
Added threading in 12f6544 My testing shows about a 70% speed increase, let me know if this is noticeable or if you have any issues

Times in milliseconds
Elapsed time: 0.6133244000084233 Without threading
Elapsed time: 0.17638780002016574 With threading

**Comment by esbe1175** [comment]
It's much, much better now. Managed to get into a triple prismatic game and hit think fast in one of my rerolls.
Won that game because of this!

I think the last thing holding it back now is the speed at which it buys the champions. it's like there's a substantial delay between detecting and buying the champions.

**Comment by jfd02** [comment]
It may be the library I'm using for mouse movement. I'll look into it and see if there are any alternatives that may have better performance

**Comment by esbe1175** [comment]
Turns out pydirectinput comes with a 0.1 second pause on all actions that take a _pause argument by default.

[https://github.com/learncodebygaming/pydirectinput/blob/master/pydirectinput/__init__.py#L9](https://github.com/learncodebygaming/pydirectinput/blob/master/pydirectinput/__init__.py#L9)
```
# Constants for failsafe check and pause

FAILSAFE = True
FAILSAFE_POINTS = [(0, 0)]
PAUSE = 0.1  # Tenth-second pause by default.
```

May have something to do with it.

I put pydirectinput.PAUSE = 0.02 at the beginning of mk_functions.py, and gave it 0.06 on specifically the moveTo function since that takes longer to execute.

It's probably too fast at the execution part now, though. As sometimes it rerolls before succesfully buying all champions (which is due to my edits. Doesn't do it without.)

Thought i'd tell you what i found.
